routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=>['auth', 'umg', 'estado'] ],
function(){ 
    Route::get('/','AdminController@index')->name('dashboard');

    Route::get('publicaciones', 'PublicacionesController@index')->name('admin.publicaciones.index');
    Route::post('publicaciones', 'PublicacionesController@store')->name('admin.publicaciones.store');
    Route::get('publicaciones/{publicacion}', 'PublicacionesController@edit')->name('admin.publicaciones.edit');
    Route::put('publicaciones/{publicacion}', 'PublicacionesController@update')->name('admin.publicaciones.update');
    Route::get('publicaciones/create', 'PublicacionesController@create')->name('admin.publicaciones.create');
    Route::delete('publicaciones/{publicacion}', 'PublicacionesController@destroy')->name('admin.publicaciones.destroy');
    Route::post('publicaciones/{publicacion}/activar', 'PublicacionesController@activar')->name('admin.publicaciones.activar');

    Route::post('publicaciones/{publicacion}/archivos', 'ArchivosController@store')->name('admin.publicaciones.archivos.store');
    Route::delete('archivos/{archivo}', 'ArchivosController@destroy')->name('admin.archivos.destroy');
    

    Route::get('catedraticos', 'CatedraticosController@index')->name('admin.catedraticos.index');
    Route::post('catedraticos', 'CatedraticosController@store')->name('admin.catedraticos.store');
    Route::get('catedraticos/{catedratico}', 'CatedraticosController@edit')->name('admin.catedraticos.edit');
    Route::put('catedraticos/{catedratico}', 'CatedraticosController@update')->name('admin.catedraticos.update');
    Route::get('catedraticos/create', 'CatedraticosController@create')->name('admin.catedraticos.create');
    Route::delete('catedraticos/{catedratico}', 'CatedraticosController@destroy')->name('admin.catedraticos.destroy');

    Route::get('personales_administrativos', 'PersonalesAdministrativosController@index')->name('admin.personales_administrativos.index');
    Route::post('personales_administrativos', 'PersonalesAdministrativosController@store')->name('admin.personales_administrativos.store');
    Route::get('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@edit')->name('admin.personales_administrativos.edit');
    Route::put('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@update')->name('admin.personales_administrativos.update');
    Route::get('personales_administrativos/create', 'PersonalesAdministrativosController@create')->name('admin.personales_administrativos.create');
    Route::delete('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@destroy')->name('admin.personales_administrativos.destroy');

    /*Route::get('facultades', 'FacultadesController@index')->name('admin.facultades.index');
    Route::post('facultades', 'FacultadesController@store')->name('admin.facultades.store');
    Route::get('facultades/create', 'FacultadesController@create')->name('admin.facultades.create');
    Route::delete('facultades/{facultad}', 'FacultadesController@destroy')->name('admin.facultades.destroy');
    Route::put('facultades/{facultad}', 'FacultadesController@update')->name('admin.facultades.update');
    Route::get('facultades/{facultad}', 'FacultadesController@edit')->name('admin.facultades.edit');*/

    Route::resource('facultades','FacultadesController',['except'=>'show', 'as'=>'admin', 'singular'=>'facultad'])->parameters([
        'facultades' =>'facultad'
    ]);

    Route::resource('users', 'UsersController',['as' => 'admin']);

    Route::middleware('role:Admin')
    ->put('users/{user}/roles', 'UsersRolesController@update')
    ->name('admin.users.roles.update');

    Route::middleware('role:Admin')
    ->put('users/{user}/permissions', 'UsersPermissionsController@update')
    ->name('admin.users.permissions.update');

    Route::get('modo_mantenimiento', 'AdminController@mantenimiento')->name('admin.mantenimiento');

});

Route::get('descarga/{archivo}', 'Admin\ArchivosController@descarga')->name('archivos.descarga');
Route::get('ver/{archivo}', 'Admin\ArchivosController@show')->name('archivos.show');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Registration Routes...
///Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/redirect', 'Auth\SocialAuthGoogleController@redirect');
Route::get('/callback', 'Auth\SocialAuthGoogleController@callback');

//RUTAS FRONTEND

Route::get('/', 'PagesController@home')->name('pages.home');    

Route::get('facultades', 'PagesController@facultades')->name('pages.facultades');   
Route::get('archivo', 'PagesController@archivo')->name('pages.archivo'); 



Route::get('blog/{publicacion}', 'PublicacionesController@show')->name('publicaciones.show');
Route::get('categorias/{categoria}', 'CategoriasController@show')->name('categorias.show');


Route::get('ingenieria', 'PagesController@ingenieria')->name('pages.ingenieria');
Route::get('ciencias_economicas', 'PagesController@ciencias_economicas')->name('pages.ciencias_economicas');
Route::get('trabajo_social', 'PagesController@trabajo_social')->name('pages.trabajo_social');
Route::get('escuela_criminalista', 'PagesController@escuela_criminalista')->name('pages.escuela_criminalista');
Route::get('ciencias_de_la_administracion', 'PagesController@ciencias_de_la_administracion')->name('pages.administracion');
Route::get('ciencias_juridicas_sociales', 'PagesController@ciencias_juridicas_sociales')->name('pages.derecho');

//RUTAS PARA EL CHAT
/*
Route::get('/conversaciones','PagesController@conversaciones')->middleware('auth')->name('chat');
Route::get('user/register',['uses'=>'UserController@register','as'=>'user.register']);
Route::resource('conversation','ConversationController');
Route::resource('message','MessageController');*/

resources/views/admin/dashboard.blade.php
@extends('admin.layoutadmin')

@section('content')

<h1>Dashboard</h1>
<div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3>{{$users->count()}}</h3>

        <p>Usuarios Registrados</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="{{route('admin.users.index')}}" class="small-box-footer">
        Mas info <i class="fa fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-yellow"><i class="fa fa-files-o"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Archivos subidos</span>
        <span class="info-box-number">{{$archivos->count()}}</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
      <span class="info-box-icon bg-blue"><i class="fa fa-flag-o"></i></span>

      <div class="info-box-content">
        <span class="info-box-text">Publicaciones</span>
        <span class="info-box-number">{{$publicaciones->count()}}</span>
      </div>
      <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
  </div>
@stop

resources/views/admin/layoutadmin.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin | UMG</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{asset('adminlte/bootstrap/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  
  @stack('styles')

  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect.
  -->
  <link rel="stylesheet" href="{{asset('adminlte/css/skins/skin-blue.min.css')}}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>UMG</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">

    <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
      
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{{ auth()->user()->url }}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs"> {{ auth()->user()->name }} -- {{ optional(auth()->user()->roles->first())->name }} </span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{{ auth()->user()->url }}" class="img-circle" alt="User Image">

                <p>
                  {{ auth()->user()->name }} -- Rol : {{ optional(auth()->user()->roles->first())->name }}
                  <small>Desde {{ auth()->user()->created_at->format('d/M/Y') }}</small>
                </p>
              </li>

              <li class="user-footer">
                <form  method="POST" action=" {{ route('logout') }} ">
                  {{ csrf_field() }}
                  <button class="btn btn-default btn-flat btn-block">Cerrar sesion</button>
                </form>
              </li>
    
            </ul>

          </li>
        </ul>

      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">

        <div class="pull-left image" style="height:39px">
          <img src="{{ auth()->user()->url }}" class="img-circle" alt="User Image">
        </div>

        <div class="pull-left info">
          <p> {{ auth()->user()->name }} </p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>

      </div>

      <!-- Sidebar Menu -->

      @include('admin.partials.nav')

      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    
    @yield('header')

    <!-- Main content -->
    <section class="content">

      @if(session()->has('flash'))
        <div class="alert alert-success">{{ session('flash') }}</div>
      
      @endif

      @yield('content')

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018 <a href="#">Benjamin Morales</a>.</strong> All rights reserved.
  </footer>
 <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.3 -->
<script src="{{asset('adminlte/plugins/jQuery/jquery-2.2.3.min.js')}}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{asset('adminlte/bootstrap/js/bootstrap.min.js')}}"></script>

@unless(request()->is('admin/publicaciones/*'))
    @include('admin.publicaciones.create')
@endunless

@unless(request()->is('admin/catedraticos/*'))
    @include('admin.catedraticos.create')
@endunless

@unless(request()->is('admin/facultades/*'))
    @include('admin.facultades.create')
@endunless

@unless(request()->is('admin/personales_administrativos/*'))
    @include('admin.personales_administrativos.create')
@endunless

@stack('scripts')

<!-- AdminLTE App -->
<script src="{{asset('adminlte/js/app.min.js')}}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>