routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=>['auth', 'umg', 'estado'] ],
function(){ 
    Route::get('/','AdminController@index')->name('dashboard');

    Route::get('publicaciones', 'PublicacionesController@index')->name('admin.publicaciones.index');
    Route::post('publicaciones', 'PublicacionesController@store')->name('admin.publicaciones.store');
    Route::get('publicaciones/{publicacion}', 'PublicacionesController@edit')->name('admin.publicaciones.edit');
    Route::put('publicaciones/{publicacion}', 'PublicacionesController@update')->name('admin.publicaciones.update');
    Route::get('publicaciones/create', 'PublicacionesController@create')->name('admin.publicaciones.create');
    Route::delete('publicaciones/{publicacion}', 'PublicacionesController@destroy')->name('admin.publicaciones.destroy');
    Route::post('publicaciones/{publicacion}/activar', 'PublicacionesController@activar')->name('admin.publicaciones.activar');

    Route::post('publicaciones/{publicacion}/archivos', 'ArchivosController@store')->name('admin.publicaciones.archivos.store');
    Route::delete('archivos/{archivo}', 'ArchivosController@destroy')->name('admin.archivos.destroy');
    

    Route::get('catedraticos', 'CatedraticosController@index')->name('admin.catedraticos.index');
    Route::post('catedraticos', 'CatedraticosController@store')->name('admin.catedraticos.store');
    Route::get('catedraticos/{catedratico}', 'CatedraticosController@edit')->name('admin.catedraticos.edit');
    Route::put('catedraticos/{catedratico}', 'CatedraticosController@update')->name('admin.catedraticos.update');
    Route::get('catedraticos/create', 'CatedraticosController@create')->name('admin.catedraticos.create');
    Route::delete('catedraticos/{catedratico}', 'CatedraticosController@destroy')->name('admin.catedraticos.destroy');

    Route::get('personales_administrativos', 'PersonalesAdministrativosController@index')->name('admin.personales_administrativos.index');
    Route::post('personales_administrativos', 'PersonalesAdministrativosController@store')->name('admin.personales_administrativos.store');
    Route::get('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@edit')->name('admin.personales_administrativos.edit');
    Route::put('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@update')->name('admin.personales_administrativos.update');
    Route::get('personales_administrativos/create', 'PersonalesAdministrativosController@create')->name('admin.personales_administrativos.create');
    Route::delete('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@destroy')->name('admin.personales_administrativos.destroy');

    /*Route::get('facultades', 'FacultadesController@index')->name('admin.facultades.index');
    Route::post('facultades', 'FacultadesController@store')->name('admin.facultades.store');
    Route::get('facultades/create', 'FacultadesController@create')->name('admin.facultades.create');
    Route::delete('facultades/{facultad}', 'FacultadesController@destroy')->name('admin.facultades.destroy');
    Route::put('facultades/{facultad}', 'FacultadesController@update')->name('admin.facultades.update');
    Route::get('facultades/{facultad}', 'FacultadesController@edit')->name('admin.facultades.edit');*/

    Route::resource('facultades','FacultadesController',['except'=>'show', 'as'=>'admin', 'singular'=>'facultad'])->parameters([
        'facultades' =>'facultad'
    ]);

    Route::resource('users', 'UsersController',['as' => 'admin']);

    Route::middleware('role:Admin')
    ->put('users/{user}/roles', 'UsersRolesController@update')
    ->name('admin.users.roles.update');

    Route::middleware('role:Admin')
    ->put('users/{user}/permissions', 'UsersPermissionsController@update')
    ->name('admin.users.permissions.update');

    Route::get('modo_mantenimiento', 'AdminController@mantenimiento')->name('admin.mantenimiento');

});

Route::get('descarga/{archivo}', 'Admin\ArchivosController@descarga')->name('archivos.descarga');
Route::get('ver/{archivo}', 'Admin\ArchivosController@show')->name('archivos.show');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Registration Routes...
///Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/redirect', 'Auth\SocialAuthGoogleController@redirect');
Route::get('/callback', 'Auth\SocialAuthGoogleController@callback');

//RUTAS FRONTEND

Route::get('/', 'PagesController@home')->name('pages.home');    

Route::get('facultades', 'PagesController@facultades')->name('pages.facultades');   
Route::get('archivo', 'PagesController@archivo')->name('pages.archivo'); 



Route::get('blog/{publicacion}', 'PublicacionesController@show')->name('publicaciones.show');
Route::get('categorias/{categoria}', 'CategoriasController@show')->name('categorias.show');


Route::get('ingenieria', 'PagesController@ingenieria')->name('pages.ingenieria');
Route::get('ciencias_economicas', 'PagesController@ciencias_economicas')->name('pages.ciencias_economicas');
Route::get('trabajo_social', 'PagesController@trabajo_social')->name('pages.trabajo_social');
Route::get('escuela_criminalista', 'PagesController@escuela_criminalista')->name('pages.escuela_criminalista');
Route::get('ciencias_de_la_administracion', 'PagesController@ciencias_de_la_administracion')->name('pages.administracion');
Route::get('ciencias_juridicas_sociales', 'PagesController@ciencias_juridicas_sociales')->name('pages.derecho');

//RUTAS PARA EL CHAT
/*
Route::get('/conversaciones','PagesController@conversaciones')->middleware('auth')->name('chat');
Route::get('user/register',['uses'=>'UserController@register','as'=>'user.register']);
Route::resource('conversation','ConversationController');
Route::resource('message','MessageController');*/

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'facultad_id', 'estado',
    ];

    public function facultad()
    {
        return $this->belongsTo(Facultad::class); //usuario pertenece a facultad
    }
    
    public function publicaciones()
    {
        return $this->hasMany(Publicacion::class); //usuario tiene muchas publicaciones
    }

    public function conversations()
    {
        return \App\Conversation::where('user1',$this->id)->orWhere('user2',$this->id)->get();
    }
    public function messages()
    {
        return $this->hasMany('App\Message');
    }

    public function scopePermitido($query)
    {
        if( auth()->user()->can('view', $this) )
        {
            return $query;
        }

        return $query->where('id', auth()->id());
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Facultad;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view',$user);
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update',$user);

        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name', 'id');
        $facultades = Facultad::all();
        return view('admin.users.edit', compact('user', 'roles','permissions','facultades'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $this->authorize('update',$user);

        $data = $request->validate([
            'name' => 'required',
            'email' => ['required', Rule::unique('users')->ignore($user->id)],
            'facultad_id' => 'required'
        ]);

        if(auth()->user()->hasRole('Admin'))
        {
            $this->validate($request, [
                'estado' => 'required'
            ]);

            $user->estado = $request['estado'];
            $user->save();
        }

        $user->update($data);

        return redirect()->route('admin.users.edit', $user)->withFlash('Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('delete', $user);

        $user->delete();
        return redirect()->route('admin.users.index')->withFlash('usuario eliminado');
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layoutadmin')

@section('content')
    <div class="row">
       <div class="col-md-6">
           <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Datos personales</h3>
                </div>

                <div class="box-body">
                    @if ($errors->any())

                        <ul class="list-group">
                            @foreach ($errors->all() as $error)
                                <li class="list-group-item list-group-item-danger">
                                    {{$error}}
                                </li>                                
                            @endforeach
                        </ul>
                        
                    @endif
                    <form method="POST" action="{{route('admin.users.update', $user) }}">
                    {{csrf_field()}} {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input name="name" value="{{ old('name', $user->name)}}" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input name="email" value="{{ old('email', $user->email)}}" class="form-control" type="email">
                        </div>

                        <div class="form-group">
                            <label>Facultades</label>
                                <select class="form-control" name="facultad_id">
                                    <option value="">Selecciona Facultad</option>
                                        @foreach($facultades as $facultad)
                                            <option value="{{ $facultad->id }}"
                                            {{old('facultad_id', $user->facultad_id ) == $facultad->id ? 'selected': ''}}
                                            >{{ $facultad->nombre }}</option>

                                        @endforeach
                                </select>
                        </div>

                        @role('Admin')

                        <div class="form-group">
                            <label>Estado</label>
                                <select class="form-control" name="estado">
                                    <option value="">Selecciona estado</option>
                                    <option value="1" {{old('estado', $user->estado ) == '1' ? 'selected': ''}}> Activo </option>
                                    <option value="0" {{old('estado', $user->estado ) == '0' ? 'selected': ''}}> Inactivo </option>
                                </select>
                        </div>

                        @endrole

                        <div class="form-group">
                            <button class="btn btn-primary btn-block" type="submit">Actualizar Usuario</button>
                        </div>

                        
                    </form>
                </div>
           </div>
       </div>

       <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3>Roles</h3>
                </div>

                <div class="box-body">

                    @role('Admin')

                    <form method="POST" action="{{ route('admin.users.roles.update', $user)}}">
                    {{ csrf_field() }} {{method_field('PUT')}}
                         @foreach ($roles as $role)
                            <div class="checkbox">
                                <label>
                                    <input name="roles[]" type="checkbox" value="{{$role->name}}" 
                                    {{$user->roles->contains($role->id) ? 'checked': ''}}>
                                    {{ $role->name}} <br>
                                    <small class="text-muted">{{$role->permissions->pluck('name')->implode(', ')}}</small>
                                </label>
                            </div>
                        @endforeach

                        <button class="btn btn-primary btn-block">Actualizar roles</button>
                    </form>
                    @else
                        <ul class="list-group">
                            @forelse ($user->roles as $role)
                                <li class="list-group-item">{{ $role->name}}</li>
                            @empty
                                <li class="list-group-item">No tiene roles</li>                                 
                            @endforelse
                        </ul>
                    @endrole
                   
                </div>
            </div>

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3>Permisos</h3>
                </div>

                <div class="box-body">

                    @role('Admin')
                    <form method="POST" action="{{ route('admin.users.permissions.update', $user)}}">
                    {{ csrf_field() }} {{method_field('PUT')}}
                         @foreach ($permissions as $id =>$name)
                            <div class="checkbox">
                                <label>
                                    <input name="permissions[]" type="checkbox" value="{{$name}}" 
                                    {{$user->permissions->contains($id) ? 'checked': ''}}>
                                    {{ $name}}
                                </label>
                            </div>
                        @endforeach

                        <button class="btn btn-primary btn-block">Actualizar Permisos</button>
                    </form>
                   @else
                        <ul class="list-group">
                            @forelse ($user->permissions as $permission)
                                <li class="list-group-item">{{ $permission->name}}</li>
                            @empty
                                <li class="list-group-item">No tiene permisos asignados</li>

                            @endforelse
                        </ul>
                    @endrole
                   
                </div>
            </div>
       </div> 
    </div>
    
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layoutadmin')

@section('header')
<section class="content-header">
    <h1>
      Listado de Usuarios
      <small>Todas los usuarios</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> Inicio</a></li>
      <li class="active">Usuarios</li>
    </ol>
  </section>

  @endsection

@section('content')

<div class="box">
    <div class="box-header">
      <h3 class="box-title">Listado de Usuarios</h3>

      {{--@can('create', new App\User)

      <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#userModal">
        <i class="fa fa-plus"></i>Agregar Usuario</button>
      @endcan --}}
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="users-table" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Estado</th>
              <th>Facultad</th>
              <th>Roles</th>
              <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
                    @foreach($users as $user)
      
                      <tr>
                          <td>{{$user->id}}</td>
                          <td>{{$user->name}}</td>
                           @if($user->estado == 1 )
                          <td>Activo</td>

                          @else
                          <td>Inactivo</td>
                          @endif
                          <td>{{$user->facultad->nombre }}</td>
                          <td>{{$user->getRoleNames()->implode(', ') }}</td>
                          
                          <td>
                          <a href="{{route('admin.users.show', $user)}}"
                              class="btn btn-default btn-sm"
                          ><i class="fa fa-eye"></i></a>

                          @can('update', $user)

                          <a href="{{ route('admin.users.edit', $user) }}"
                              class="btn btn-info btn-sm"
                              ><i class="fa fa-pencil"></i></a>

                        @endcan

                          {{--@can('delete', $user)
                          <form method="POST" 
                          action="{{ route('admin.users.destroy', $user) }}"
                          style="display: inline">
                          {{ csrf_field() }} {{ method_field('DELETE') }}

                          <button class="btn btn-danger btn-sm"
                            onclick="return confirm('Estas seguro de querer eliminar este usuario?')"
                          ><i class="fa fa-times"></i></button>

                          </form>

                          @endcan--}}

                          </td>
                      </tr>
      
                    @endforeach
      
            </tbody>
            
          </table>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->

@endsection


@push('styles')
 <!-- DataTables -->
 <link rel="stylesheet" href="{{asset('adminlte/plugins/datatables/dataTables.bootstrap.css')}}">
 
@endpush

@push('scripts')
<!-- DataTables -->
<script src="{{asset('adminlte/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('adminlte/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>

<!-- page script -->
<script>
    $(function () {
      $('#users-table').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "scrollX": true,

        "language": {
            "emptyTable": "No hay datos disponibles en la tabla",
            "infoEmpty":      "Mostrando 0 a 0 de 0 entradas",           
            "info": "Mostrando pagina _PAGE_ de _PAGES_",
            "search": "Buscar:",
              "paginate": {
              "first":      "Primer",
              "last":       "Ultimo",
              "next":       "Siguiente",
              "previous":   "Anterior"
        }
        }
      });
    });

  </script>

  @endpush

resources/views/admin/users/show.blade.php
@extends('admin.layoutadmin')

@section('content')

    <div class="row">
        <div class="col-md-3">
          <div class="box box-primary">
            <div class="box-body box-profile">
              <img class="profile-user-img img-responsive img-circle" src="{{ auth()->user()->url }}" alt="{{$user->name}}">

              <h3 class="profile-username text-center">{{$user->name}}</h3>

              <p class="text-muted text-center">{{$user->getRoleNames()->implode(', ')}}</p>

              <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Email</b> <a class="pull-right">{{$user->email}}</a>
                </li>
                <li class="list-group-item">
                  <b>Publicaciones</b> <a class="pull-right">{{$user->publicaciones->count() }}</a>
                </li>
                @if ($user->roles->count())

                   <li class="list-group-item">
                      <b>Roles</b> <a class="pull-right">{{$user->getRoleNames()->implode(', ')}}</a>
                   </li>

                @endif


                <li class="list-group-item">
                  <b>Facultad</b> <a class="pull-right">{{$user->facultad->nombre}}</a>
                </li>
               
              </ul>

              @can('update',$user)
              <a href="{{route('admin.users.edit', $user)}}" class="btn btn-primary btn-block"><b>Editar</b></a>
              @endcan

            </div>
            <!-- /.box-body -->
          </div>
        </div>

        <div class="col-md-3">
          <div class="box prymary">
            <div class="box-header with-border">
              <h3 class="box-title">Publicaciones</h3>
            </div>

            <div class="box-body">
              @forelse ($user->publicaciones as $publicacion)

                <strong>{{ $publicacion->titulo}}</strong><br>
                <small class="text-muted">Publicado el {{ $publicacion->publicado_el->format('d-m-y')}}</small>
                <p class="text-muted">{{$publicacion->extracto}}</p>
                @unless($loop->last)
                  <hr>
                @endunless

              @empty
                <small class="test-muted">No tiene ninguna publicacion</small>

              @endforelse
              
            </div>
          
                    
          </div>
        </div>

        <div class="col-md-3">
          <div class="box prymary">
            <div class="box-header with-border">
              <h3 class="box-title">Roles</h3>
            </div>

            <div class="box-body">
              @forelse ($user->roles as $role)

                <strong>{{ $role->name}}</strong>

                @if( $role->permissions->count())
                  <br>
                  <small class="text-muted">
                    Permisos: {{$role->permissions->pluck('name')->implode(', ')}}
                  </small>

                @endif
                
                @unless($loop->last)
                  <hr>
                @endunless

              @empty
                <small class="text-muted">No tiene ningun rol asociado</small>

              @endforelse
              
            </div>
          
                    
          </div>
        </div>

        <div class="col-md-3">
          <div class="box prymary">
            <div class="box-header with-border">
              <h3 class="box-title">Permisos adicionales</h3>
            </div>

            <div class="box-body">
              @forelse ($user->permissions as $permission)

                <strong>{{ $permission->name}} </strong><br>
                @unless($loop->last)
                  <hr>
                @endunless
              @empty

              <small class="text-muted">No tiene permisos adicionales</small>

              @endforelse
              
            </div>
          
                    
          </div>
        </div>
    </div>

@endsection