routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=>['auth', 'umg', 'estado'] ],
function(){ 
    Route::get('/','AdminController@index')->name('dashboard');

    Route::get('publicaciones', 'PublicacionesController@index')->name('admin.publicaciones.index');
    Route::post('publicaciones', 'PublicacionesController@store')->name('admin.publicaciones.store');
    Route::get('publicaciones/{publicacion}', 'PublicacionesController@edit')->name('admin.publicaciones.edit');
    Route::put('publicaciones/{publicacion}', 'PublicacionesController@update')->name('admin.publicaciones.update');
    Route::get('publicaciones/create', 'PublicacionesController@create')->name('admin.publicaciones.create');
    Route::delete('publicaciones/{publicacion}', 'PublicacionesController@destroy')->name('admin.publicaciones.destroy');
    Route::post('publicaciones/{publicacion}/activar', 'PublicacionesController@activar')->name('admin.publicaciones.activar');

    Route::post('publicaciones/{publicacion}/archivos', 'ArchivosController@store')->name('admin.publicaciones.archivos.store');
    Route::delete('archivos/{archivo}', 'ArchivosController@destroy')->name('admin.archivos.destroy');
    

    Route::get('catedraticos', 'CatedraticosController@index')->name('admin.catedraticos.index');
    Route::post('catedraticos', 'CatedraticosController@store')->name('admin.catedraticos.store');
    Route::get('catedraticos/{catedratico}', 'CatedraticosController@edit')->name('admin.catedraticos.edit');
    Route::put('catedraticos/{catedratico}', 'CatedraticosController@update')->name('admin.catedraticos.update');
    Route::get('catedraticos/create', 'CatedraticosController@create')->name('admin.catedraticos.create');
    Route::delete('catedraticos/{catedratico}', 'CatedraticosController@destroy')->name('admin.catedraticos.destroy');

    Route::get('personales_administrativos', 'PersonalesAdministrativosController@index')->name('admin.personales_administrativos.index');
    Route::post('personales_administrativos', 'PersonalesAdministrativosController@store')->name('admin.personales_administrativos.store');
    Route::get('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@edit')->name('admin.personales_administrativos.edit');
    Route::put('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@update')->name('admin.personales_administrativos.update');
    Route::get('personales_administrativos/create', 'PersonalesAdministrativosController@create')->name('admin.personales_administrativos.create');
    Route::delete('personales_administrativos/{personal_administrativo}', 'PersonalesAdministrativosController@destroy')->name('admin.personales_administrativos.destroy');

    /*Route::get('facultades', 'FacultadesController@index')->name('admin.facultades.index');
    Route::post('facultades', 'FacultadesController@store')->name('admin.facultades.store');
    Route::get('facultades/create', 'FacultadesController@create')->name('admin.facultades.create');
    Route::delete('facultades/{facultad}', 'FacultadesController@destroy')->name('admin.facultades.destroy');
    Route::put('facultades/{facultad}', 'FacultadesController@update')->name('admin.facultades.update');
    Route::get('facultades/{facultad}', 'FacultadesController@edit')->name('admin.facultades.edit');*/

    Route::resource('facultades','FacultadesController',['except'=>'show', 'as'=>'admin', 'singular'=>'facultad'])->parameters([
        'facultades' =>'facultad'
    ]);

    Route::resource('users', 'UsersController',['as' => 'admin']);

    Route::middleware('role:Admin')
    ->put('users/{user}/roles', 'UsersRolesController@update')
    ->name('admin.users.roles.update');

    Route::middleware('role:Admin')
    ->put('users/{user}/permissions', 'UsersPermissionsController@update')
    ->name('admin.users.permissions.update');

    Route::get('modo_mantenimiento', 'AdminController@mantenimiento')->name('admin.mantenimiento');

});

Route::get('descarga/{archivo}', 'Admin\ArchivosController@descarga')->name('archivos.descarga');
Route::get('ver/{archivo}', 'Admin\ArchivosController@show')->name('archivos.show');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Registration Routes...
///Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/redirect', 'Auth\SocialAuthGoogleController@redirect');
Route::get('/callback', 'Auth\SocialAuthGoogleController@callback');

//RUTAS FRONTEND

Route::get('/', 'PagesController@home')->name('pages.home');    

Route::get('facultades', 'PagesController@facultades')->name('pages.facultades');   
Route::get('archivo', 'PagesController@archivo')->name('pages.archivo'); 



Route::get('blog/{publicacion}', 'PublicacionesController@show')->name('publicaciones.show');
Route::get('categorias/{categoria}', 'CategoriasController@show')->name('categorias.show');


Route::get('ingenieria', 'PagesController@ingenieria')->name('pages.ingenieria');
Route::get('ciencias_economicas', 'PagesController@ciencias_economicas')->name('pages.ciencias_economicas');
Route::get('trabajo_social', 'PagesController@trabajo_social')->name('pages.trabajo_social');
Route::get('escuela_criminalista', 'PagesController@escuela_criminalista')->name('pages.escuela_criminalista');
Route::get('ciencias_de_la_administracion', 'PagesController@ciencias_de_la_administracion')->name('pages.administracion');
Route::get('ciencias_juridicas_sociales', 'PagesController@ciencias_juridicas_sociales')->name('pages.derecho');

//RUTAS PARA EL CHAT
/*
Route::get('/conversaciones','PagesController@conversaciones')->middleware('auth')->name('chat');
Route::get('user/register',['uses'=>'UserController@register','as'=>'user.register']);
Route::resource('conversation','ConversationController');
Route::resource('message','MessageController');*/

app/Conversation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Conversation extends Model
{
    public function messages()
    {
        return $this->hasMany('App\Message')->orderBy('created_at', 'asc');
    }
    public function user1()
    {
        return $this->belongsTo('App\User','user1');
    }
    public function user2()
    {
        return $this->belongsTo('App\User','user2');
    }
}

app/Http/Controllers/ConversationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Conversation;
use LRedis;
use App\Http\Requests;
use Auth;
use App\User;


class ConversationController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function store(Request $request){
        $c1 = Conversation::where('user1',Auth::user()->id)->where('user2',$request->user_id)->count();
        $c2 = Conversation::where('user2',Auth::user()->id)->where('user1',$request->user_id)->count();
        if($c1 != 0 || $c2 != 0)
            return redirect()->back();

        $c = new Conversation();
        $c->user1 = Auth::user()->id;
        $c->user2 = $request->user_id;
        $c->save();

        return redirect()->back();
    }
    public function show($id){
        $conversationp = Conversation::findOrFail($id);

        $users = User::where('id','!=',Auth::user()->id)->get();
        $conversations = Auth::user()->conversations();

        if($conversationp->user1 == Auth::user()->id || $conversationp->user2 == Auth::user()->id)

            return view('conversation.chat',compact('conversationp', 'conversations', 'users'));

        return redirect()->back();
    }
}

resources/views/conversation/chat.blade.php
@extends('layout')
@push('chat_css')
<link rel="stylesheet" href="{{asset('css/chat.css')}}">
@endpush

@section('content')
<div class="row chat-row">

    <div class="col-md panel-conversaciones">
        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading text-chat">Usuarios</div>

                    <div class="panel-body">
                        @foreach($users as $user)
                            <div class="row">
                            <div class="col-md-6">
                            {{$user->name}}
                            </div>
                            <div class="col-md-6">
                            {{Form::open(['url'=>route('conversation.store')])}}
                            {{Form::hidden('user_id',$user->id)}}
                            {{Form::submit('add',['class'=>'form-control'])}}
                            {{Form::close()}}
                            </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading text-chat">Conversaciones</div>

                    <div class="panel-body">
                        @foreach($conversations as $conversation)
                            <a href="{{route('conversation.show',$conversation->id)}}">
                            {{($conversation->user1()->first()->id==Auth::user()->id)?$conversation->user2()->first()->name:$conversation->user1()->first()->name}}
                            </a>
                            <hr/>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="contenedor col-md">

        <div class="col-md-offset-4 col-md-12 chat-movil">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-12">

                        <a data-toggle="collapse" href="#chatCollapse" role="button" aria-expanded="true" aria-controls="chatCollapse">
                        <p class="text-chat">Estas hablando con: {{($conversationp->user1()->first()->id==Auth::user()->id)?$conversationp->user2()->first()->name:$conversationp->user1()->first()->name}}</p>
                        </a>
                            
                        </div>
                    </div>
                </div>

            <div class="collapse" id="chatCollapse">
                    <div class="panel-body" id="panel-body">
                    @foreach($conversationp->messages as $message)
                        @if($message->user_id!=Auth::user()->id)
                        <div class="row row-not-owner">
                            <div class="message {{ ($message->user_id!=Auth::user()->id)?'not_owner':'owner'}}">
                                {{$message->text}}<br/>
                                <b>{{$message->created_at->diffForHumans()}}</b>
                            </div>
                        </div>
                        @else
                        <div class="row row-owner">
                            <div class="message {{ ($message->user_id!=Auth::user()->id)?'not_owner':'owner'}}">
                                {{$message->text}}<br/>
                                <b>{{$message->created_at->diffForHumans()}}</b>
                            </div>
                        </div>
                        @endif
                    @endforeach
                </div>
                <div class="panel-footer">
                        <textarea id="msg" class="form-control col-8" placeholder="Escribe tu mensaje" rows="1"></textarea>
                        <input type="hidden" id="csrf_token_input" value="{{csrf_token()}}"/>
                        <br/>
                            <div class="col-md-offset-4 col-md-4">
                            <button class="btn btn-primary btn-block" onclick="button_send_msg()">Enviar</button>
                            </div>
                </div>
            </div>
                
            </div>
        </div>
    </div>
</div>



@endsection

@push('chat_js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js"></script>
    <script>
        var socket = io.connect('http://127.0.0.1:8890');
        socket.emit('add user', {'client':{{Auth::user()->id}},'conversation':{{$conversationp->id}} });

        socket.on('message', function (data) {
            $('#panel-body').append(
                    '<div class="row row-not-owner">'+
                    '<div class="message not_owner">'+
                    data.msg+'<br/>'+
                    '<b>now</b>'+
                    '</div>'+
                    '</div>');

            scrollToEnd();

         });
    </script>
    <script>
        $(document).ready(function(){
            scrollToEnd();

            $(document).keypress(function(e) {
                if(e.which == 13) {
                    var msg = $('#msg').val();
                    $('#msg').val('');//reset
                    send_msg(msg);
                }
            });
        });

        function button_send_msg(){
            var msg = $('#msg').val();
            $('#msg').val('');//reset
            send_msg(msg);
        }


        function send_msg(msg){
            $.ajax({
                headers: { 'X-CSRF-Token' : $('#csrf_token_input').val() },
                type: "POST",
                url: "{{route('message.store')}}",
                data: {
                    'text': msg,
                    'conversation_id':{{$conversationp->id}},
                },
                success: function (data) {
                    if(data==true){

                        $('#panel-body').append(
                                '<div class="row row-owner">'+
                                '<div class="message owner">'+
                                msg+'<br/>'+
                                '<b>ora</b>'+
                                '</div>'+
                                '</div>');

                        scrollToEnd();
                    }
                },
                error: function (e) {
                    console.log(e);
                }
            });
        }

        function scrollToEnd(){
            var d = $('#panel-body');
            d.scrollTop(d.prop("scrollHeight"));
        }


$('.hide-chat-box').click(function(){
$('.chat-content').slideToggle();
});
    </script>
@endpush

resources/views/conversation/conversation.blade.php
@extends('layout')
<!--CAROUSEL INICIO-->
@push('chat_css')
<link rel="stylesheet" href="{{asset('css/chat.css')}}">
@endpush
<div class="row justify-content-center">
    <div class="col-sm-0"></div>
</div>


@section('content')
	<section class="posts container">
	{{-- 	
			@if (isset ($titulo))
			<h3>{{ $titulo }}</h3>
			@endif


		@foreach($publicaciones as $publicacion)

		<article class="post">

			@include( $publicacion->viewType('home'))

			<div class="content-post">
				
				

				@include('publicaciones.header')

			
				<h1>{{$publicacion->titulo}}</h1>
				<div class="divider"></div>
				<p>{{$publicacion->extracto}}</p>
				
				<footer class="container-flex space-between">
					<div class="read-more">
						<a href="{{ route('publicaciones.show', $publicacion) }}" class="text-uppercase c-green">Leer mas</a>					</div>
					</div>

				</footer>
			</div>
		</article>

		@endforeach   --}}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading text-chat">Usuarios</div>

                <div class="panel-body">
                    @foreach($users as $user)
                        <div class="row">
                        <div class="col-md-6">
                        {{$user->name}}
                        </div>
                        <div class="col-md-6">
                        {{Form::open(['url'=>route('conversation.store')])}}
                        {{Form::hidden('user_id',$user->id)}}
                        {{Form::submit('add',['class'=>'form-control'])}}
                        {{Form::close()}}
                        </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading text-chat">Conversaciones</div>

                <div class="panel-body">
                    @foreach($conversations as $conversation)
                        <a href="{{route('conversation.show',$conversation->id)}}">
                        {{($conversation->user1()->first()->id==Auth::user()->id)?$conversation->user2()->first()->name:$conversation->user1()->first()->name}}
                        </a>
                        <hr/>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>

	</section><!-- fin del div.posts.container -->

	<div class="container">
		{{--{{ $publicaciones->links('vendor/pagination/default') }}--}}
	</div>
	
    
@stop